### PR TITLE
add test for image-file

### LINKED ISSUE #23: Coverage Tests [image-file.ts]
Write coverage tests in Jest for `image-file.ts` located in the `src` directory.

### PR DESCRIPTION
**Pull request by tomconder**
Fixes #23 

## Proposed Changes

  - add test for image-file

I decided to take on a more complicated jest test. In order to make it work I had to make a few changes:

- set target to `es2019` to get the test to compile
- minor refactor of cache-file so that the axios response can be mocked
- add `.cache` and `.idea` to gitignore

Note that this creates a .cache directory as part of the test. I considered creating a "clean" script to package.json that looks like this: 

```
"clean": "rimraf .cache coverage",
```

### CODE REVIEW

**Comment by ccalamos** [comment]
Thanks for the PR, I will look into this soon!

**Comment by ccalamos** [comment]
@tomconder I have added updates to your PR on branch `tomconder-add-test-for-image-file`, however I would love for you to check it out and then create a new PR where all you do is update in the `package.json` the version from `1.4.7` => `1.4.8` and submit a new PR that I will merge. Other than that it all looks great!

**Comment by tomconder** [comment]
You got it! I do not seem to have permission to create a PR directly against branch `tomconder-add-test-for-image-file`.  So I merged it into this PR, bumped the version number to 1.4.8 and ran `yarn format` (no appreciable change since I assume you already ran it).

**Comment by ccalamos** [comment]
This works out great! Thank you!

**Pull request merged**
